spring:
  liquibase:
    enabled: true
    change-log: classpath:db/master.xml
  application:
    name: student-portal-spring
  datasource:
    url: jdbc:mysql://localhost:3306/student_portal
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:rootroot}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  servlet:
    multipart:
      max-file-size: 10MB
  profiles:
    active:

server:
  port: 8081

student:
  portal:
    upload:
      image:
        directory:
          path: /Users/karen/Data/lessons/Java-2025/spring/student-portal-spring/upload_images/
logging:
  file:
    name: /Users/karen/Data/lessons/Java-2025/spring/student-portal-spring/log/student-portal-spring.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 3

  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    com.example.studentportalspring.controller: DEBUG
